use rand::{thread_rng, Rng};

/* trait on str allowing for case to be changed */
use util::StringCase;

const TITLE_NUM: u32 = 666;

const TITLE_PARTS: [(&'static str, &'static str); 666] = [
    (r"Succeed With ", r" In 24 Hours"),
    (r"Marriage And ", r" Have More In Common Than You Think"),
    (r"Fascinating ", r" Tactics That Can Help Your Business Grow"),
    (r"10 Secret Things You Didn't Know About ", r""),
    (r"Sick And Tired Of Doing ", r" The Old Way? Read This"),
    (r"How To Teach ", r" Better Than Anyone Else"),
    (r"Winning Tactics For ", r""),
    (r"Who Else Wants To Enjoy ", r""),
    (r"Never Suffer From ", r" Again"),
    (r"Guaranteed No Stress ", r""),
    (r"Rules Not To Follow About ", r""),
    (r"A Surprising Tool To Help You ", r""),
    (r"What Can You Do About ", r" Right Now"),
    (r"Sexy ", r""),
    (r"How To Earn $398/Day Using ", r""),
    (r"It's All About (The) ", r""),
    (r"", r": An Incredibly Easy Method That Works For All"),
    (r"5 Ways Of ", r" That Can Drive You Bankrupt - Fast!"),
    (r"Want More Money? Start ", r""),
    (r"The Philosophy Of ", r""),
    (r"What Everyone Ought To Know About ", r""),
    (r"How To Sell ", r""),
    (r"Why Most ", r" Fail"),
    (r"Fast-Track Your ", r""),
    (r"Take The Stress Out Of ", r""),
    (r"", r" Is Essential For Your Success. Read This To Find Out Why"),
    (r"The Secret of ", r""),
    (r"How To Teach ", r" Like A Pro"),
    (r"How To Make More ", r" By Doing Less"),
    (r"Why Some People Almost Always Make/Save Money With ", r""),
    (r"The Number One Reason You Should (Do) ", r""),
    (r"Learn To (Do) ", r" Like A Professional"),
    (r"The Secrets To ", r""),
    (r"Find Out Now, What Should You Do For Fast ", r"?"),
    (r"Your Key To Success: ", r""),
    (r"3 Tips About ", r" You Can't Afford To Miss"),
    (r"5 Actionable Tips on ", r" And Twitter."),
    (r"Secrets To Getting ", r" To Complete Tasks Quickly And Efficiently"),
    (r"Using 7 ", r" Strategies Like The Pros"),
    (r"", r" Expert Interview"),
    (r"Wondering How To Make Your ", r" Rock? Read This!"),
    (r"3 Mistakes In ", r" That Make You Look Dumb"),
    (r"There’s Big Money In ", r""),
    (r"The Hidden Mystery Behind ", r""),
    (r"Proof That ", r" Is Exactly What You Are Looking For"),
    (r"Why ", r" Is No Friend To Small Business"),
    (r"", r" Strategies For Beginners"),
    (r"Master (Your) ", r" in 5 Minutes A Day"),
    (r"5 Reasons ", r" Is A Waste Of Time"),
    (r"Cracking The ", r" Code"),
    (r"Quick and Easy Fix For Your ", r""),
    (r"Should Fixing ", r" Take 60 Steps?"),
    (r"Why Everything You Know About ", r" Is A Lie"),
    (r"Got Stuck? Try These Tips To Streamline Your ", r""),
    (r"3 Ways Twitter Destroyed My ", r" Without Me Noticing"),
    (r"Can You Pass The ", r" Test?"),
    (r"How You Can (Do) ", r" Almost Instantly"),
    (r"The Untold Secret To ", r" In Less Than Ten Minutes"),
    (r"5 Surefire Ways ", r" Will Drive Your Business Into The Ground"),
    (r"4 Ways You Can Grow Your Creativity Using ", r""),
    (r"Want A Thriving Business? Focus On ", r"!"),
    (r"Who Else Wants To Know The Mystery Behind ", r"?"),
    (r"10 Funny ", r" Quotes"),
    (r"What You Can Learn From Bill Gates About ", r""),
    (r"The Lazy Man's Guide To ", r""),
    (r"How To Learn ", r""),
    (r"5 Ways To Get Through To Your ", r""),
    (r"The Ultimate Deal On ", r""),
    (r"", r" Shortcuts - The Easy Way"),
    (r"", r" Is Crucial To Your Business. Learn Why!"),
    (r"Never Lose Your ", r" Again"),
    (r"Savvy|Smart|Sexy People Do ", r" :)"),
    (r"Best ", r" Android/iPhone Apps"),
    (r"Top 10 Tips With ", r""),
    (r"How You Can (Do) ", r" In 24 Hours Or Less For Free"),
    (r"", r": This Is What Professionals Do"),
    (r"Where Can You Find Free ", r" Resources"),
    (r"Warning: These 9 Mistakes Will Destroy Your ", r""),
    (r"How To Become Better With ", r" In 10 Minutes"),
    (r"Here Is What You Should Do For Your ", r""),
    (r"3 Simple Tips For Using ", r" To Get Ahead Your Competition"),
    (r"", r": What A Mistake!"),
    (r"Want To Step Up Your ", r"? You Need To Read This First"),
    (r"Double Your Profit With These 5 Tips on ", r""),
    (r"If You Do Not (Do)", r" Now, You Will Hate Yourself Later"),
    (r"What Is ", r" and How Does It Work?"),
    (r"How To Save Money with ", r"?"),
    (r"Find Out How I Cured My ", r" In 2 Days"),
    (r"Get Rid of ", r" For Good"),
    (r"How To Get (A) Fabulous ", r" On A Tight Budget"),
    (r"Who Else Wants To Be Successful With ", r""),
    (r"Top 25 Quotes On ", r""),
    (r"Why You Really Need (A) ", r""),
    (r"Old School ", r""),
    (r"Fall In Love With ", r""),
    (r"What Can Instagramm Teach You About ", r""),
    (r"The Ultimate Secret Of ", r""),
    (r"Short Story: The Truth About ", r""),
    (r"You Don't Have To Be A Big Corporation To Start ", r""),
    (r"Apply These 5 Secret Techniques To Improve ", r""),
    (r"Being A Star In Your Industry Is A Matter Of ", r""),
    (r"Interesting Facts I Bet You Never Knew About ", r""),
    (r"How To Start ", r" With Less Than $100"),
    (r"How To Use ", r" To Desire"),
    (r"15 Unheard Ways To Achieve Greater ", r""),
    (r"Need More Time? Read These Tips To Eliminate ", r""),
    (r"Boost Your ", r" With These Tips"),
    (r"At Last, The Secret To ", r" Is Revealed"),
    (r"Don't Fall For This ", r" Scam"),
    (r"What Make ", r" Don't Want You To Know"),
    (r"Here's A Quick Way To Solve A Problem with ", r""),
    (r"10 Unforgivable Sins Of ", r""),
    (r"How To Win Friends And Influence People with ", r""),
    (r"10 Ways To Reinvent Your ", r""),
    (r"Little Known Ways To Rid Yourself Of ", r""),
    (r"5 Romantic ", r" Ideas"),
    (r"", r" An Incredibly Easy Method That Works For All"),
    (r"Fear? Not If You Use ", r" The Right Way!"),
    (r"Best Make ", r" You Will Read This Year (in 2015)"),
    (r"Beware The ", r" Scam"),
    (r"10 Ways To Immediately Start Selling ", r""),
    (r"Don't Be Fooled By ", r""),
    (r"Now You Can Have Your ", r" Done Safely"),
    (r"3 Ways Create Better ", r" With The Help Of Your Dog"),
    (r"10 Tips That Will Make You Influential In ", r""),
    (r"15 Tips For ", r" Success"),
    (r"5 Ways ", r" Will Help You Get More Business"),
    (r"What Alberto Savoia Can Teach You About ", r""),
    (r"The Secret of Successful ", r""),
    (r"7 Easy Ways To Make ", r" Faster"),
    (r"Are You Embarrassed By Your ", r" Skills? Here's What To Do"),
    (r"How To Turn Your ", r" From Zero To Hero"),
    (r"Use ", r" To Make Someone Fall In Love With You"),
    (r"15 Lessons About ", r" You Need To Learn To Succeed"),
    (r"5 Incredibly Useful ", r" Tips For Small Businesses"),
    (r"Picture Your ", r" On Top. Read This And Make It So"),
    (r"Best 50 Tips For ", r""),
    (r"Here Is A Quick Cure For ", r""),
    (r"The Quickest & Easiest Way To ", r""),
    (r"In 10 Minutes, I'll Give You The Truth About ", r""),
    (r"13 Myths About ", r""),
    (r"52 Ways To Avoid ", r" Burnout"),
    (r"Revolutionize Your ", r" With These Easy-peasy Tips"),
    (r"Now You Can Buy An App That is Really Made For ", r""),
    (r"How To Win Buyers And Influence Sales with ", r""),
    (r"How I Improved My ", r" In One Day"),
    (r"Is ", r" Worth [$] To You?"),
    (r"A Guide To ", r" At Any Age"),
    (r"How To Improve At ", r" In 60 Minutes"),
    (r"2 Things You Must Know About ", r""),
    (r"Are You Making These ", r" Mistakes?"),
    (r"10 Best Practices For ", r""),
    (r"11 Methods Of ", r" Domination"),
    (r"These 5 Simple ", r" Tricks Will Pump Up Your Sales Almost Instantly"),
    (r"The Truth Is You Are Not The Only Person Concerned About ", r""),
    (r"OMG! The Best ", r" Ever!"),
    (r"Believe In Your ", r" Skills But Never Stop Improving"),
    (r"Lies And Damn Lies About ", r""),
    (r"14 Days To A Better ", r""),
    (r"Find A Quick Way To ", r""),
    (r"How To Deal With(A) Very Bad ", r""),
    (r"Learn Exactly How We Made ", r" Last Month"),
    (r"Answered: Your Most Burning Questions About ", r""),
    (r"How To Start A Business With ", r""),
    (r"5 Brilliant Ways To Teach Your Audience About ", r""),
    (r"Can You Really Find ", r" (on the Web)?"),
    (r"5 Best Ways To Sell ", r""),
    (r"The Ugly Truth About ", r""),
    (r"How To Make Your ", r" Look Like A Million Bucks"),
    (r"10 Warning Signs Of Your ", r" Demise"),
    (r"", r": The Samurai Way"),
    (r"", r" Made Simple - Even Your Kids Can Do It"),
    (r"7 Ways To Keep Your ", r" Growing Without Burning The Midnight Oil"),
    (r"What Can You Do To Save Your ", r" From Destruction By Social Media?"),
    (r"Why ", r" Is The Only Skill You Really Need"),
    (r"Top 10 Tips To Grow Your ", r""),
    (r"Why You Never See ", r" That Actually Works"),
    (r"Does ", r" Sometimes Make You Feel Stupid?"),
    (r"5 Simple Steps To An Effective ", r" Strategy"),
    (r"Learn How To Start ", r""),
    (r"How To Make Your Product Stand Out With ", r""),
    (r"The Biggest Lie In ", r""),
    (r"17 Tricks About ", r" You Wish You Knew Before"),
    (r"How To Make Your ", r" Look Amazing In 5 Days"),
    (r"Avoid The Top 10 Mistakes Made By Beginning ", r""),
    (r"Ho To (Do) ", r" Without Leaving Your Office(House)."),
    (r"", r" - So Simple Even Your Kids Can Do It"),
    (r"Remarkable Website - ", r" Will Help You Get There"),
    (r"How To Win Clients And Influence Markets with ", r""),
    (r"Essential ", r" Smartphone Apps"),
    (r"Everything You Wanted to Know About ", r" and Were Too Embarrassed to Ask"),
    (r"Here Is A Method That Is Helping ", r""),
    (r"You Will Thank Us - 10 Tips About ", r" You Need To Know"),
    (r"How To Lose Money With ", r""),
    (r"The Truth About ", r" In 3 Minutes"),
    (r"3 Ways To Master ", r" Without Breaking A Sweat"),
    (r"Read This Controversial Article And Find Out More About ", r""),
    (r"", r" Your Way To Success"),
    (r"Listen To Your Customers. They Will Tell You All About ", r""),
    (r"How To Quit ", r" In 5 Days"),
    (r"9 Ways ", r" Can Make You Invincible"),
    (r"The Ultimate Guide To ", r""),
    (r"Congratulations! Your ", r" Is (Are) About To Stop Being Relevant"),
    (r"What Your Customers Really Think About Your ", r"?"),
    (r"", r" Is Bound To Make An Impact In Your Business"),
    (r"", r" Smackdown!"),
    (r"How We Improved Our ", r" In One Week(Month, Day)"),
    (r"This Study Will Perfect Your ", r": Read Or Miss Out"),
    (r"Take 10 Minutes to Get Started With ", r""),
    (r"The A - Z Guide Of ", r""),
    (r"7 and a Half Very Simple Things You Can Do To Save ", r""),
    (r"The Death Of ", r" And How To Avoid It"),
    (r"Some People Excel At ", r" And Some Don't - Which One Are You?"),
    (r"Now You Can Have The ", r" Of Your Dreams – Cheaper/Faster Than You Ever Imagined"),
    (r"22 Tips To Start Building A ", r" You Always Wanted"),
    (r"The Untapped Gold Mine Of ", r" That Virtually No One Knows About"),
    (r"", r" And Love Have 4 Things In Common"),
    (r"Why ", r" Succeeds"),
    (r"Death, ", r" And Taxes"),
    (r"3 Easy Ways To Make ", r" Faster"),
    (r"You Can Thank Us Later - 3 Reasons To Stop Thinking About ", r""),
    (r"How To Turn ", r" Into Success"),
    (r"Have You Heard? ", r" Is Your Best Bet To Grow"),
    (r"3 Things Everyone Knows About ", r" That You Don't"),
    (r"How To Buy (A) ", r" On A Tight Budget"),
    (r"", r"? It's Easy If You Do It Smart"),
    (r"9 Ridiculous Rules About ", r""),
    (r"", r" Works Only Under These Conditions"),
    (r"SuperEasy Ways To Learn Everything About ", r""),
    (r"What You Should Have Asked Your Teachers About ", r""),
    (r"The Secret Of ", r""),
    (r"Why My ", r" Is Better Than Yours"),
    (r"Secrets To ", r" – Even In This Down Economy"),
    (r"5 Brilliant Ways To Use ", r""),
    (r"Why Ignoring ", r" Will Cost You Time and Sales"),
    (r"How I Improved My ", r" In One Easy Lesson"),
    (r"How To Handle Every ", r" Challenge With Ease Using These Tips"),
    (r"How ", r" Made Me A Better Salesperson"),
    (r"3 ", r" Secrets You Never Knew"),
    (r"What Everyone Must Know About ", r""),
    (r"Get Rid of ", r" Once and For All"),
    (r"5 Ways You Can Get More ", r" While Spending Less"),
    (r"Improve(Increase) Your ", r" In 3 Days"),
    (r"The Next 3 Things To Immediately Do About ", r""),
    (r"The Best Way To ", r""),
    (r"Where Is The Best ", r"?"),
    (r"3 Ways You Can Reinvent ", r" Without Looking Like An Amateur"),
    (r"Get The Most Out of ", r" and Facebook"),
    (r"10 Things You Have In Common With ", r""),
    (r"World Class Tools Make ", r" Push Button Easy"),
    (r"101 Ideas For ", r""),
    (r"If You Want To Be A Winner, Change Your ", r" Philosophy Now!"),
    (r"Don't Just Sit There! Start ", r""),
    (r"Could This Report Be The Definitive Answer To Your ", r"?"),
    (r"27 Ways To Improve ", r""),
    (r"Top 3 Ways To Buy A Used ", r""),
    (r"12 Questions Answered About ", r""),
    (r"5 Secrets: How To Use ", r" To Create A Successful Business(Product)"),
    (r"Never Changing ", r" Will Eventually Destroy You"),
    (r"", r" And The Chuck Norris Effect"),
    (r"No More Mistakes With ", r""),
    (r"5 Sexy Ways To Improve Your ", r""),
    (r"Clear And Unbiased Facts About ", r" (Without All the Hype)"),
    (r"How To Find The Right ", r" For Your Specific Product(Service)."),
    (r"Get Better ", r" Results By Following 3 Simple Steps"),
    (r"What Zombies Can Teach You About ", r""),
    (r"To People That Want To Start ", r" But Are Affraid To Get Started"),
    (r"The ", r" Mystery Revealed"),
    (r"Why Most People Will Never Be Great At ", r""),
    (r"The Lazy Way To ", r""),
    (r"Why I Hate ", r""),
    (r"Little Known Ways to ", r""),
    (r"Proof That ", r" Really Works"),
    (r"The Secrets To Finding World Class Tools For Your ", r" Quickly"),
    (r"Everything You Wanted to Know About ", r" and Were Afraid To Ask"),
    (r"", r" Adventures"),
    (r"The Anthony Robins Guide To ", r""),
    (r"", r": Do You Really Need It? This Will Help You Decide!"),
    (r"Turn Your ", r" Into A High Performing Machine"),
    (r"The Ultimate Guide To ", r""),
    (r"I Don't Want To Spend This Much Time On ", r". How About You?"),
    (r"", r" Iphone Apps"),
    (r"The ", r" That Wins Customers"),
    (r"Make Your ", r"A Reality"),
    (r"At Last, The Secret To ", r" Is Revealed"),
    (r"2 Ways You Can Use ", r" To Become Irresistible To Customers"),
    (r"Open The Gates For ", r" By Using These Simple Tips"),
    (r"Stop Wasting Time And Start ", r""),
    (r"7 Rules About ", r" Meant To Be Broken"),
    (r"5 Things To Do Immediately About ", r""),
    (r"Do ", r" Better Than Barack Obama"),
    (r"The Untold Secret To Mastering ", r" In Just 3 Days"),
    (r"The Single Most Important Thing You Need To Know About ", r""),
    (r"5 Problems Everyone Has With ", r" – How To Solved Them"),
    (r"If ", r" Is So Terrible, Why Don't Statistics Show It?"),
    (r"3 Ways To Have (A) More Appealing ", r""),
    (r"Learn Exactly How I Improved ", r" In 2 Days"),
    (r"Avoid The Top 10 ", r" Mistakes"),
    (r"How To Take The Headache Out Of ", r""),
    (r"5 Easy Ways You Can Turn ", r" Into Success"),
    (r"10 Laws Of ", r""),
    (r"", r" Guides And Reports"),
    (r"9 Easy Ways To ", r" Without Even Thinking About It"),
    (r"", r" For Dollars Seminar"),
    (r"10 Step Checklist for ", r""),
    (r"The Advantages Of Different Types Of ", r""),
    (r"Are You Actually Doing Enough ", r"?"),
    (r"The Critical Difference Between ", r" and Google"),
    (r"7 Practical Tactics to Turn ", r" Into a Sales Machine"),
    (r"", r" Report: Statistics and Facts"),
    (r"10 Facts Everyone Should Know About ", r""),
    (r"The Best Advice You Could Ever Get About ", r""),
    (r"2015 Is The Year Of ", r""),
    (r"", r" - What Can Your Learn From Your Critics"),
    (r"", r" - Relax, It's Play Time!"),
    (r"10 Effective Ways To Get More Out Of ", r""),
    (r"7 Things I Would Do If I'd Start Again ", r""),
    (r"5 Proven ", r" Techniques"),
    (r"10 Questions On ", r""),
    (r"10 Factors That Affect ", r""),
    (r"10 Ideas About ", r" That Really Work"),
    (r"", r" - What To Do When Rejected"),
    (r"", r"! 10 Tricks The Competition Knows, But You Don't"),
    (r"The Definitive Guide To ", r""),
    (r"Does Your ", r" Goals Match Your Practices?"),
    (r"How To Spread The Word About Your ", r""),
    (r"Super Useful Tips To Improve ", r""),
    (r"Can You Spot The A ", r" Pro?"),
    (r"10 Undeniable Facts About ", r""),
    (r"Three Quick Ways To Learn ", r""),
    (r"Will ", r" Ever Die?"),
    (r"", r" - How To Be More Productive?"),
    (r"10 Reasons Your ", r" Is Not What It Should Be"),
    (r"11 Things Twitter Wants Yout To Forget About ", r""),
    (r"3 Guilt Free ", r" Tips"),
    (r"Master The Art Of ", r" With These 3 Tips"),
    (r"How To Guide: ", r" Essentials For Beginners"),
    (r"7 Strange Facts About ", r""),
    (r"Top 10 Key Tactics The Pros Use For ", r""),
    (r"More on Making a Living Off of ", r""),
    (r"Time-tested Ways To ", r""),
    (r"", r" Is Your Worst Enemy. 10 Ways To Defeat It"),
    (r"", r" Reviewed: What Can One Learn From Other's Mistakes"),
    (r"10 Reasons Why You Are Still An Amateur At ", r""),
    (r"Must Have Resources For ", r""),
    (r"", r" For Profit"),
    (r"10 Creative Ways You Can Improve Your ", r""),
    (r"A Good ", r" Is..."),
    (r"Arguments For Getting Rid Of ", r""),
    (r"", r" Strategies Revealed"),
    (r"The World's Worst Advice On ", r""),
    (r"The 10 Key Elements In ", r""),
    (r"20 ", r" Mistakes You Should Never Make"),
    (r"", r" Predictions For 2015"),
    (r"Take Advantage Of ", r" - Read These 10 Tips"),
    (r"To Click Or Not To Click: ", r" And Blogging"),
    (r"Signs You Made A Great Impact On ", r""),
    (r"7 Incredible ", r" Transformations"),
    (r"", r" Etics and Etiquette"),
    (r"Secrets About ", r""),
    (r"10 Shortcuts For ", r" That Gets Your Result In Record Time"),
    (r"", r" - What Do Those Stats Really Mean?"),
    (r"", r" - The Six Figure Challenge"),
    (r"10 Trendy Ways To Improve On ", r""),
    (r"", r" Explained"),
    (r"Make The Most Out Of ", r""),
    (r"Mind Blowing Method On ", r""),
    (r"", r" Promotion 101"),
    (r"Extreme ", r""),
    (r"15 No Cost Ways To Get More With ", r""),
    (r"", r" Services - How To Do It Right"),
    (r"3 Kinds Of ", r": Which One Will Make The Most Money?"),
    (r"20 Places To Get Deals On ", r""),
    (r"59% Of The Market Is Interested In ", r""),
    (r"", r" Data We Can All Learn From"),
    (r"The Most Common Mistakes People Make With ", r""),
    (r"21 Effective Ways To Get More Out Of ", r""),
    (r"What's Wrong With ", r""),
    (r"5 Emerging ", r" Trends To Watch In 2016"),
    (r"Seductive ", r""),
    (r"3 Reasons Why Facebook Is The Worst Option For ", r""),
    (r"10 Essential Strategies To ", r""),
    (r"Where To Start With ", r"?"),
    (r"Believing Any Of These 10 Myths About ", r" Keeps You From Growing"),
    (r"Where Will ", r" Be 6 Months From Now?"),
    (r"", r" - Are You Prepared For A Good Thing?"),
    (r"Marketing And ", r""),
    (r"The Best 5 Examples Of ", r""),
    (r"", r" Hopes and Dreams"),
    (r"10 Solid Reasons To Avoid ", r""),
    (r"Add These 10 Mangets To Your ", r""),
    (r"What's New About ", r""),
    (r"", r" - Pay Attentions To These 10 Signals"),
    (r"Why ", r" Doesn't Work…For Everyone"),
    (r"10 Facts Everyone Should Know About ", r""),
    (r"Top 5 Books About ", r""),
    (r"How Google Uses ", r" To Grow Bigger"),
    (r"", r" Money Experiment"),
    (r"10 Awesome Tips About ", r" From Unlikely Websites"),
    (r"10 Things I Wish I Knew About ", r""),
    (r"Are You ", r" The Right Way? These 5 Tips Will Help You Answer"),
    (r"10 Powerful Tips To Help You ", r" Better"),
    (r"10 Reasons You Need To Stop Stressing About ", r""),
    (r"Why ", r" Is A Tactic Not A Strategy"),
    (r"", r" Doesn't Have To Be Hard. Read These 9 Tricks Go Get A Head Start."),
    (r"Top 10 ", r" Accounts To Follow On Twitter"),
    (r"Don't ", r" Unless You Use These 10 Tools"),
    (r"Is ", r" Making Me Rich?"),
    (r"", r" Resources: google.com (website)"),
    (r"Five Rookie ", r" Mistakes You Can Fix Today"),
    (r"5 Habits Of Highly Effective ", r""),
    (r"Amateurs ", r" But Overlook A Few Simple Things"),
    (r"7 Life-Saving Tips About ", r""),
    (r"The Impact Of ", r" On Your Customers/Followers"),
    (r"7 Facebook Pages To Follow About ", r""),
    (r"Read This To Change How You ", r""),
    (r"What $325 Buys You In ", r""),
    (r"10 Ways to Make Your ", r" Easier"),
    (r"What Do You Want ", r" To Become?"),
    (r"Free Advice On ", r""),
    (r"When ", r" Competition is Good"),
    (r"Cash For ", r""),
    (r"", r": Back To Basics"),
    (r"Easy Steps To ", r" Of Your Dreams"),
    (r"Are You ", r" The Best You Can? 10 Signs Of Failure"),
    (r"10 Reasons Why Having An Excellent ", r" Is Not Enough"),
    (r"Sins Of ", r""),
    (r"These 10 Hacks Will Make You(r) ", r" (Look) Like A Pro"),
    (r"", r" For Money"),
    (r"How To Find The Time To ", r" On Twitter"),
    (r"", r" For Dollars"),
    (r"", r": An Incredibly Easy Method That Works For All"),
    (r"3 Short Stories You Didn't Know About ", r""),
    (r"22 Very Simple Things You Can Do To Save Time With ", r""),
    (r"Se7en Worst ", r" Techniques"),
    (r"Strange Facts About ", r""),
    (r"15 Creative Ways You Can Improve Your ", r""),
    (r"Are You Struggling With ", r"? Let's Chat"),
    (r"5 Incredible ", r" Examples"),
    (r"How to Grow Your ", r" Income"),
    (r"", r" For Sale – How Much Is Yours Worth?"),
    (r"", r" 2.0 - The Next Step"),
    (r"10 Biggest ", r" Mistakes You Can Easily Avoid"),
    (r"", r" Conferences"),
    (r"", r" And The Art Of Time Management"),
    (r"", r" Creates Experts"),
    (r"21 New Age Ways To ", r""),
    (r"A New Model For ", r""),
    (r"", r" - Choosing The Right Strategy"),
    (r"Building Relationships With ", r""),
    (r"Advanced ", r""),
    (r"Welcome to a New Look Of ", r""),
    (r"Getting The Best Software To Power Up Your ", r""),
    (r"One Tip To Dramatically Improve You(r) ", r""),
    (r"10 Tips That Will Change The Way You ", r""),
    (r"Here Are 7 Ways To Better ", r""),
    (r"The Advanced Guide To ", r""),
    (r"Favorite ", r" Resources For 2015"),
    (r"What Every ", r" Need To Know About Facebook"),
    (r"Don't Waste Time! 5 Facts To Start ", r""),
    (r"Earning a Six Figure Income From ", r""),
    (r"The Complete Process of ", r""),
    (r"8 Ways To ", r" Without Breaking Your Bank"),
    (r"The Most Common ", r" Debate Isn't As Simple As You May Think"),
    (r"Top 10 Websites To Look For ", r""),
    (r"Who is Your ", r" Customer?"),
    (r"Is It Time to Talk More About ", r"?"),
    (r"5 Things People Hate About ", r""),
    (r"What Are The 5 Main Benefits Of ", r""),
    (r"4 Most Common Problems With ", r""),
    (r"", r" - It Never Ends, Unless..."),
    (r"The Ultimate Strategy To ", r""),
    (r"25 Questions You Need To Ask About ", r""),
    (r"Top 10 YouTube Clips About ", r""),
    (r"", r" Stats: These Numbers Are Real"),
    (r"Take Home Lessons On ", r""),
    (r"25 Best Things About ", r""),
    (r"Free Advice On Profitable ", r""),
    (r"How To Make Money From The ", r" Phenomenon"),
    (r"50 Best Tweets Of All Time About ", r""),
    (r"The Evolution Of ", r""),
    (r"How I Got Started With ", r""),
    (r"", r" Gets A Redesign"),
    (r"A Short Course In ", r""),
    (r"", r" - Not For Everyone"),
    (r"The 3 Really Obvious Ways To ", r" Better That You Ever Did"),
    (r"The Most (and Least) Effective Ideas In ", r""),
    (r"Time Is Running Out! Think About These 10 Ways To Change Your ", r""),
    (r"", r" And Other Products"),
    (r"The World's Best ", r" You Can Actually Buy"),
    (r"", r" Once, "),
    (r"", r" Helps You Achieve Your Dreams"),
    (r"When Is The Right Time To Start ", r""),
    (r"Apply Any Of These 10 Secret Techniques To Improve ", r""),
    (r"", r": The Google Strategy"),
    (r"Random ", r" Tip"),
    (r"Less = More With ", r""),
    (r"When Professionals Run Into Problems With ", r", This Is What They Do"),
    (r"25 Of The Punniest ", r" Puns You Can Find"),
    (r"How Did We Get There? The History Of ", r" Told Through Tweets"),
    (r"Open Mike on ", r""),
    (r"100 Lessons Learned From the Pros On ", r""),
    (r"", r" in 2015 – Predictions"),
    (r"5 Ways To Simplify ", r""),
    (r"", r" Without Driving Yourself Crazy"),
    (r"A Simple Plan For ", r""),
    (r"Dreaming Of ", r""),
    (r"What's Right About ", r""),
    (r"Successful Stories You Didn’t Know About ", r""),
    (r"Thinking About ", r"? 10 Reasons Why It's Time To Stop!"),
    (r"When ", r" Businesses Grow Too Quickly"),
    (r"My Biggest ", r" Lesson"),
    (r"", r": Keep It Simple (And Stupid)"),
    (r"The No. 1 ", r" Mistake You're Making (and 4 Ways To Fix It)"),
    (r"7 Days To Improving The Way You ", r""),
    (r"5 ", r" Issues And How To Solve Them"),
    (r"5 Critical Skills To (Do) ", r" Loss Remarkably Well"),
    (r"Beware: 10 ", r" Mistakes"),
    (r"", r" Abuse - How Not To Do It"),
    (r"Fears of a Professional ", r""),
    (r"", r" Changes: 5 Actionable Tips"),
    (r"", r": The Easy Way"),
    (r"", r" Not Resulting In Financial Prosperity"),
    (r"44 Inspirational Quotes About ", r""),
    (r"How 5 Stories Will Change The Way You Approach ", r""),
    (r"More on ", r""),
    (r"Improve Your ", r" Skills"),
    (r"What Could ", r" Do To Make You Switch?"),
    (r"Simple Steps To A 10 Minute ", r""),
    (r"10 Mesmerizing Examples Of ", r""),
    (r"The Most Important Elements Of ", r""),
    (r"Ridiculously Simple Ways To Improve Your ", r""),
    (r"10 Horrible Mistakes To Avoid When You (Do) ", r""),
    (r"The Pros And Cons Of ", r""),
    (r"", r" Consulting – What The Heck Is That?"),
    (r"Introducing The Simple Way To ", r""),
    (r"The #1 ", r" Mistake, Plus 7 More Lessons"),
    (r"Need More Inspiration With ", r"? Read this!"),
    (r"Must Have List Of ", r" Networks"),
    (r"10 Lessons You Can Learn From Bing About ", r""),
    (r"The Complete Guide To Understanding ", r""),
    (r"The Business Of ", r""),
    (r"Why It's Easier To Fail With ", r" Than You Might Think"),
    (r"10 DIY ", r" Tips You May Have Missed"),
    (r"9 Super Useful Tips To Improve ", r""),
    (r"The Biggest Disadvantage Of Using ", r""),
    (r"How to Create Your ", r" Strategy [Blueprint]"),
    (r"", r" 15 Minutes A Day To Grow Your Business"),
    (r"", r" Review"),
    (r"", r"Like An Expert. Follow These 5 Steps To Get There"),
    (r"Crazy ", r": Lessons From The Pros"),
    (r"10 Small Changes That Will Have A Huge Impact On Your ", r""),
    (r"How Google Is Changing How We Approach ", r""),
    (r"Super Easy Simple Ways The Pros Use To Promote ", r""),
    (r"", r" Blueprint - Rinse And Repeat"),
    (r"Did You Start ", r" For Passion or Money?"),
    (r"One Surprisingly Effective Way To ", r""),
    (r"Understanding ", r""),
    (r"", r" Fears – Death"),
    (r"", r" – Lessons Learned From Google"),
    (r"", r" The Right Way"),
    (r"Mastering The Way Of ", r" Is Not An Accident - It's An Art"),
    (r"7 Amazing ", r" Hacks"),
    (r"The Future Of ", r""),
    (r"", r" Ethics"),
    (r"10 Alternatives To ", r""),
    (r"3 More Cool Tools For ", r""),
    (r"", r": Is Not That Difficult As You Think"),
    (r"Take Advantage Of ", r" - Read These 10 Tips"),
    (r"The Hollistic Aproach To ", r""),
    (r"", r" Question: Does Size Matter?"),
    (r"", r" Cheet Sheet"),
    (r"The 5 Secrets To Effective ", r""),
    (r"Cats, Dogs and ", r""),
    (r"4 Key Tactics The Pros Use For ", r""),
    (r"Want More Out Of Your Life? ", r", "),
    (r"Poll: How Much Do You Earn From ", r"?"),
    (r"The World's Most Unusual ", r""),
    (r"5 Stylish Ideas For Your ", r""),
    (r"Triple Your Results At ", r" In Half The Time"),
    (r"Street Talk: ", r""),
    (r"12 Ways You Can ", r" Without Investing Too Much Of Your Time"),
    (r"", r" Opportunities For Everyone"),
    (r"How To Get Discovered With ", r""),
    (r"Solid Reasons To Avoid ", r""),
    (r"", r" Like A Pro With The Help Of These 5 Tips"),
    (r"The Power Of ", r""),
    (r"3 Reasons Why Having An Excellent ", r" Isn't Enough"),
    (r"Questions For/About ", r""),
    (r"The Ten Commandments Of ", r""),
    (r"Finding Customers With ", r" (Part A,B,C ... )"),
    (r"The Consequences Of Failing To ", r" When Launching Your Business"),
    (r"", r" Explained 101"),
    (r"The Etiquette of ", r""),
    (r"Attention-grabbing Ways To ", r""),
    (r"Your Weakest Link: Use It To ", r""),
    (r"", r" It! Lessons From The Oscars"),
    (r"How Much Do You Charge For ", r""),
    (r"The Business Of ", r""),
    (r"How To Be In The Top 10 With ", r""),
    (r"Some Facts About ", r" That Will Make You Feel Better"),
    (r"They Compared CPA Earnings To Those Made With ", r". It's Sad"),
    (r"Look Ma, You Can Actually Build a Bussiness With ", r""),
    (r"10 Thing I Like About ", r", But #3 Is My Favorite"),
    (r"When You Ask People About ", r" This Is What They Answer"),
    (r"Here Are 4 ", r" Tactics Everyone Believes In. Which One Do You Prefer?"),
    (r"The Real Story Behind ", r""),
    (r"Strategy For Maximizing ", r""),
    (r"Take This ", r" Test And You'll See Your Struggles. Literally"),
    (r"Here's Why 1 Million Customers In the US Are ", r""),
    (r"", r": Are You Prepared For A Good Thing?"),
    (r"The Biggest Problem in ", r#" Comes Down To This Word That Starts With "W""#),
    (r"Prepare To Laugh: ", r" Is Not Harmless As you Might Think. Take A Look At These Great Examples"),
    (r"In the Age of Information, Specializing in ", r""),
    (r"You're Welcome. Here Are 8 Noteworthy Tips About ", r""),
    (r"The Stuff About ", r" You Probably Hadn't Considered. And Really Should"),
    (r"Is It Time To Talk More ABout ", r"?"),
    (r"There's A Right Way To Talk About ", r" And There's Another Way..."),
    (r"", r": Quality vs Quantity"),
    (r"Heard Of The ", r" Effect? Here It Is"),
    (r"", r" Tip: Shake It Up"),
    (r"", r" For Fun"),
    (r"", r" Mindset. Genius Idea!"),
    (r"Try These 5 Things When You First Start ", r" (Because of Science)"),
    (r"8 Things About ", r" That You Want... Badly"),
    (r"This Test Will Show You Wheter You're An Expert in ", r" Without Knowing It. Here's How It Works"),
    (r"What Makes ", r" That Different"),
    (r"Remember Your First ", r" Lesson? I've Got Some News..."),
    (r"Top 10 Mistakes On ", r" That You Can Easlily Correct Today"),
    (r"It's The Side Of Extreme ", r" Rarely Seen, But That's Why Is Needed"),
    (r"7 Magical Mind Tricks To Help You Declutter ", r""),
    (r"Anyone Who Has A Problem With ", r" Needs To Know One Thing"),
    (r"", r": A List of 11 Things That'll Put You In a Good Mood"),
    (r"Here's the science behind A Perfect ", r""),
    (r"Are You Good At ", r"? Here's A Quick Quiz To Find Out"),
    (r"Learn Anything New From ", r" Lately? We Asked, You Answered!"),
    (r"It' Hard Enough To Do Push Ups - It's Even Harder To Do ", r""),
    (r"My Biggest ", r" Lesson"),
    (r"", r" Sucks. But You Should Probably Know More About It Than That."),
    (r"Is This ", r" Thing Really That Hard"),
    (r"Heard Of The Great ", r" BS Theory? Here Is A Great Example"),
    (r"", r" Tip: Make Yourself Available"),
    (r"Here's An Inside Look At The Latest ", r"Video That Brought Joy On YouTube"),
    (r"Nothing To See Here. Just A Bunch Of Us Agreeing a 3 Basic ", r" Rules"),
    (r"They Were Asked 3 Questions About ", r"... It's A Great Lesson"),
    (r"", r" - Does Size Matter?"),
    (r"A Smart, Educational Look At What ", r" *Really* Does In Our World"),
    (r"Improve Your ", r" Skills"),
    (r"Genius! How To Figure Out If You Should Really Do ", r""),
    (r"", r": One Question You Don't Want To Ask Anymore"),
    (r"10 Experimental And Mind-Bending ", r" Techniques That You Won't See In Textbooks"),
    (r"How Do You Define ", r"? Because This Definition Is Pretty Hard To Beat."),
    (r"13 More Reasons To Be Excited About ", r""),
    (r"What You Didn't Realize About ", r" Is Powerful - But Extremely Simple"),
    (r"Don't Get Too Excited. You May Not Be Done With ", r""),
    (r"Something Fascinating Happened After Taking Action On These 5 ", r" Tips"),
    (r"It's The Side of Extreme ", r" Rarely Seen, But That's Why It's Needed"),
    (r"7 Tips From A ", r" Pro"),
    (r"Here, Copy This Idea on ", r""),
    (r"An Analysis Of 12 ", r" Strategies... Here's What We Learned"),
    (r"5 New Definitions About ", r" You Don't Usually Want To Hear"),
    (r"The Difference Between ", r" And Search Engines"),
    (r"How Important is ", r". 10 Expert Quotes"),
    (r"", r" Experiment We Can All Learn From"),
    (r"", r": Launching Your Own Affiliate Program"),
    (r"6 Nontraditional ", r" Techniques That Are Unlike Any You've Ever Seen. Ther're Perfect.")
];

pub fn build_titles (keywords: &Vec<String>, num_titles: u32) -> Vec<String> {
    let mut rng = thread_rng();

    let mut out_titles = Vec::new();

    for _ in 0..num_titles {
        // take prefix and suffix from randomly chosen title
        let (prefix, suffix) = TITLE_PARTS[rng.gen_range::<usize>(
            // need to cast u32 as usize so that
            // SliceIndex constraints are satisfied
            0, TITLE_NUM as usize
        )];

        let title = format!(
            "{}{}{}",

            prefix,

            // from keywords..
            keywords[
                // get a random keyword
                rng.gen_range::<usize>(
                    // where index is between 0 and
                    // total number of keywords
                    0, keywords.len() as usize
                )
            ].to_capitalized(),

            suffix
        );

        out_titles.push(title);
    }

    out_titles
}